name: Pull Request - Open
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  deploy:
    name: 'Deploy Review App'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Clever Cloud Cli
        run: |
          wget https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz
          tar -xvf clever-tools-latest_linux.tar.gz
          mv clever-tools-latest_linux/clever /usr/local/bin/clever
          chmod +x /usr/local/bin/clever
      - run: clever login --token ${CLEVER_TOKEN} --secret ${CLEVER_SECRET}
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
      - run: clever create pr-${{ github.sha }} -t php --region par --alias pr-${{ github.sha }}
      - run: clever domain add flemzord-pr-${{ github.sha }}.cleverapps.io --alias pr-${{ github.sha }} 
      - run: clever addon create postgresql-addon pr-${{ github.sha }}-pgsql --link pr-${{ github.sha }} --region par 
      - run: clever scale --flavor nano --alias pr-${{ github.sha }}
      - run: clever env set CC_WEBROOT '/public' --alias pr-${{ github.sha }}
      - run: clever env set CC_POST_BUILD_HOOK 'php artisan migrate --force' --alias pr-${{ github.sha }}
      - run: clever env set APP_KEY 'base64:n/tcQ9ONifskhoZ9aLWnyYO0CHOBfsCXb+A9D8/kTzM=' --alias pr-${{ github.sha }}
      - run: clever deploy