name: Pull Request - Open
on:
  pull_request:
    types: [opened, reopened]
jobs:
  deploy:
    name: 'Deploy Review App'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Clever Cloud Cli
        run: |
          wget https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz
          tar -xvf clever-tools-latest_linux.tar.gz
          mv clever-tools-latest_linux/clever /usr/local/bin/clever
          chmod +x /usr/local/bin/clever
      - run: clever login --token ${CLEVER_TOKEN} --secret ${CLEVER_SECRET}
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
      - run: clever create pr-${{ github.event.number }} -t php --region par --alias pr-${{ github.event.number }}
      - run: clever domain add flemzord-pr-${{ github.event.number }}.cleverapps.io --alias pr-${{ github.event.number }} 
      - run: clever addon create postgresql-addon pr-${{ github.event.number }}-pgsql --link pr-${{ github.event.number }} --region par 
      - run: clever scale --flavor nano --alias pr-${{ github.event.number }}
      - run: clever env set CC_WEBROOT '/public' --alias pr-${{ github.event.number }}
      - run: clever env set CC_POST_BUILD_HOOK 'php artisan migrate --force' --alias pr-${{ github.event.number }}
      - run: clever env set APP_KEY 'base64:n/tcQ9ONifskhoZ9aLWnyYO0CHOBfsCXb+A9D8/kTzM=' --alias pr-${{ github.event.number }}
      - run: clever env set CC_PHP_VERSION '8' --alias pr-${{ github.event.number }}
      - run: sleep 60
      - run: clever deploy --alias pr-${{ github.event.number }}
      - uses: JoseThen/comment-pr@v1.1.1
        with:
          comment: 'URL for review : https://flemzord-pr-${{ github.event.number }}.cleverapps.io'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}